version: "3.7"

services:
  mariadb:
    # https://hub.docker.com/_/mariadb?tab=description&page=1&ordering=last_updated 
    container_name: etaamb_db
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - etaamb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=etaamb
      - MYSQL_PASSWORD=mariadb
      - MYSQL_USER=mariadb
    networks:
      - etaamb
    ports:
      - "3306:3306"

  steward:
    container_name: etaamb_steward
    build:
      context: ./
      target: dev
      dockerfile: ./agent/Dockerfile
    volumes:
      - ./resources:/resources
      - ./agent:/agent/
    environment:
      - DEBUG=true
      - DB_USER=mariadb
      - DB_DATA=etaamb
      - DB_PASSWORD=mariadb
      - DB_HOST=etaamb_db
      - DB_PORT=3306
    depends_on:
      - mariadb
    networks:
      - etaamb

  phpmyadmin:
    container_name: etaamb_admin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    volumes:
      - phpmyadmin_data:/var/www/html/
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - PMA_HOST=etaamb_db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=mariadb
      - PMA_ARBITRATY=1
    ports:
      - "8032:80"
    networks:
      - etaamb

  etaamb:
    container_name: etaamb_php
    build:
      context: .
      target: dev
      dockerfile: ./Dockerfile
      args:
        - SMTP_HOST=localhost
        - SMTP_PORT=25
        - SMTP_USER=null
        - SMTP_PASSWORD=null
      # command: ./misc/entrypoint.sh
    volumes:
      - ./etaamb:/app/etaamb
    environment:
      - DEBUG=true
      - DB_USER=mariadb
      - DB_DATA=etaamb
      - DB_PASSWORD=mariadb
      - DB_HOST=etaamb_db
      - DB_PORT=3306
      - ETAAMB_DOMAIN=localhost:8042
      - ETAAMB_PROTOCOL=http
      - ADMIN_MAIL=test@example.com
    ports:
      - "8042:80"
    depends_on:
      - mariadb
      - steward
    networks:
      - etaamb

volumes:
  etaamb_data:
  phpmyadmin_data:

networks:
  etaamb:
    driver: bridge
