<?php

class dict
    {

    var $langs = array (
        "fr" => array (
            'title_just_title' => 'La publication online des décisions de Justice : constats d’urgence',
            'title_just_url' => 'https://openjustice.be/2020/05/16/la-publication-online-des-decisions-de-justice-constats-durgence/',
            'numac_just_title' => 'La publication online des décisions de Justice : constats d’urgence',
            'numac_just_url' => 'https://openjustice.be/2020/05/16/la-publication-online-des-decisions-de-justice-constats-durgence/',
			'search'		=> 'rechercher',
			'index_title' => 'Bienvenue sur Etaamb | Index Global',
			'index_description' => 'Index Par Date des publications du Moniteur Belge',
			'index_quickmenu' => 'Accès rapide par date de publication',
			'index_promquickmenu' => 'Accès rapide par date de promulgation',
			'index_lasteditiontitle' => 'Contenu dernière édition:',
			'index_pubordertitle' => 'Accès par date de publication:',
			'index_promordertitle' => 'Accès par date de promulgation:',
            'index_editionmenu' => 'Accès rapide',
			'month_index_of'  => 'M.B. Index de',
			'month_index_of_pub'  => 'M.B. Index des publications de',
			'month_index_of_prom'  => 'M.B. Index des promulgations de',
			'month_description' => 'Index des jours de publication du Moniteur Belge au mois de',
			'month_1'	=> 'janvier',
			'month_2'	=> 'février',
			'month_3'	=> 'mars',
			'month_4'	=> 'avril',
			'month_5'	=> 'mai',
			'month_6'	=> 'juin',
			'month_7'	=> 'juillet',
			'month_8'	=> 'août',
			'month_9'	=> 'septembre',
			'month_10'	=> 'octobre',
			'month_11'	=> 'novembre',
			'month_12'	=> 'décembre',
			'day_1'		=> 'lundi',
			'day_2'		=> 'mardi',
			'day_3'		=> 'mercredi',
			'day_4'		=> 'jeudi',
			'day_5'		=> 'vendredi',
			'day_6'		=> 'samedi',
			'day_7'		=> 'dimanche',
			'of'		=> 'du',
			'about'		=> 'a propos',
			'about_link' => 'http://etaamb.blogspot.com/p/propos.html',
			'year_index_of' => 'M.B. Index de l\'année',
			'year_index_of_pub' => 'M.B. Index des publications de l\'année',
			'year_index_of_prom' => 'M.B. Index des promulgations de l\'année',
			'year_description'=> 'Aperçu du calendrier des jours de publicaiton du Moniteur Belge de l\'année',
			'day_index_of'  => 'M.B. Index du',
			'day_index_of_pub'  => 'M.B. Index des textes publiés le',
			'day_index_of_prom'  => 'M.B. Index des textes promulgués le',
			'day_quickmenu' => 'Accès rapide',
			'day_description' => 'Liste de tous les actes publiés au Moniteur Belge le',
			'doc_source' => 'source',
			'doc_pub'	=> 'pub.',
			'doc_prom'	=> 'prom.',
			'doc_numac' => 'numac',
			'doc_type' => 'type',
			'numac_source' => 'source',
			'numac_moniteur' => 'moniteur',
			'numac_of' 		=> ' du',
			'numac_published_on' => 'publié le',
			'numac_document_of' => 'Document du',
			'numac_referer_title' => 'Votre recherche %s',
			'numac_referer_description' => 'Les termes de votre requête (%s) sont mis en surbrillance dans le texte.',
			'numac_referer_deactivate'  => 'désactiver',
			'numac_list_title' => 'Documents pertinents retrouvés',
			'title_source' 	=> 'source',
			'title_moniteur' => 'moniteur',
			'title_of' 		=> ' du',
			'keywords_list' => 'Mots-clés',
			'etaamb_description' => '<b>Etaamb</b> propose le contenu du Moniteur Belge trié par date de publication et de promulgation, traité pour le rendre facilement lisible et imprimable, et enrichi par un contexte relationnel.',
			'linked_list' 	=> 'Textes mentionnés par ce document:',
			'reversed_list' => 'Textes qui mentionnent ce document:',
			'notype'		=> 'document',
            'title'     	=> 'Etaamb',
			'moniteur'		=> 'Moniteur',
			'my_error_title' 	=> 'Erreur de requête',
			'my_error_oops' 	=> 'Oups...',
			'my_error_descrption' => 'Erreur de requête',
			'my_error_intro' 	=> 'La requête à provoqué le message d\'erreur suivant:',
			'my_error_url'   	=> 'L\'URL suivante peut donc ne pas être correcte:',
			'my_error_balsem'	=> 'L\'erreur à étée enregistrée et sera examinée et traitée dans les plus brefs délais.',
			'my_error_general' => 'L\'URL n\'est pas reconnue par Etaamb.',
			'my_error_numac' 	=> 'Le document n\'est pas disponible dans la banque de données. <br> Il est donc inexistant, non repris dans Etaamb, ou non traduit.',
			'my_error_year_invalid' => 'Il n\'y a pas d\'éditions numériques du Moniteur Belge pour l\'année indiquée.',
			'my_error_month_invalid' => 'Il n\'y a pas d\'éditions numériques du Moniteur Belge au mois indiquée.',
			'my_error_day_invalid' => 'Il n\'y a pas d\'éditions numériques du Moniteur Belge au jour indiquée.',
			'my_error_naturalisation' => 'Pour des raisons de protection de la vie privée, le document demandé est temporairement indisponible.',
			'close'			=> 'fermer',
			'interfacewords'=> 'title numac',
			'hire_me'		=> 'Sans être en recherche active d\'un emploi, je suis toujours disponible pour des projets innovants ou des offres intéressantes.  
			Si vous avez en projet une application internet ou mobile, besoin d\'un développeur expérimenté ou simplement d\'expertise, nous pouvons sûrement en discuter.',
			'private_life'	=> 'vie privée',
			'priv_title'	=> 'Vos données apparaissent sur cette page?',
			'priv_exp'		=> 'Si vous le souhaitez, il vous est possible de demander par l\'intermédiaire du formulaire ci-dessous le retrait de vos données de ce document tel que diffusé sur etaamb.be.',
			'priv_text'		=> 'Titre du document concerné:',
			'priv_url'		=> 'Url de la page concernée:',
			'priv_comment'	=> 'Commentaires:',
			'priv_mail'		=> 'Votre adresse e-mail:',
			'priv_data'		=> 'Termes à retirer:',
			'priv_opt'		=> 'Champs optionnels',
			'priv_send'		=> 'envoyer',
			'rss_title_complete' 		=> 'Sommaire du Moniteur Belge',
			'rss_description_complete'  => 'Tout le contenu de la dernière publication du Moniteur Belge, proposé sur le site etaamb.be',
			'rss_signature'	=> 'Lisez le contenu complet sur etaamb.be !',
			'stopwords' 	=> 'alors au aucuns aussi autre avant avec avoir bon car ce cela ces ceux chaque ci comme comment dans de des du dedans dehors depuis deux devrait doit donc dos droite début elle elles en encore essai est et eu fait faites fois font force haut hors ici il ils je juste la le les leur là ma maintenant mais mes mine moins mon mot même ni nommés notre nous nouveaux ou où par parce parole pas personnes peut peu pièce plupart pour pourquoi quand que quel quelle quelles quels qui sa sans ses seulement si sien son sont sous soyez sujet sur ta tandis tellement tels tes ton tous tout trop très tu valeur voie voient vont votre vous vu ça étaient état étions été être'
            ),
        'nl' => array(
            'title_just_title' => 'Justitie digitaliseren: Call to Contribution',
            'title_just_url' => 'https://justice-pourlepeuple-doorhetvolk.be/',
            'numac_just_title' => 'Justitie digitaliseren: Call to Contribution',
            'numac_just_url' => 'https://justice-pourlepeuple-doorhetvolk.be/',
			'search'		=> 'opzoeken',
			'index_title' => 'Welkom op Etaamb | Globale Index',
			'index_description' => 'Index per Datum van de publicaties van het Belgisch Staatsblad',
			'index_quickmenu' => 'Snelle toegang op publicatiedatum',
			'index_promquickmenu' => 'Snelle toegang op datum van afkondiging',
			'index_lasteditiontitle' => 'Inhoud laatste editie:',
            'index_editionmenu' => 'Snelle toegang',
			'index_pubordertitle' => 'Toegang volgens publicatiedatum:',
			'index_promordertitle' => 'Toegang volgens datum van afkondiging:',
			'month_index_of'  => 'B.S. Index van ',
			'month_index_of_pub'  => 'B.S. Index van de publicaties van',
			'month_index_of_prom'  => 'B.S. Index van de afkondigingen van',
			'month_description' => 'Index van de dagen met publicaties van het Belgisch Staatsblad in',
									' voor de gekozen maand',
			'month_1'	=> 'januari',
			'month_2'	=> 'februari',
			'month_3'	=> 'maart',
			'month_4'	=> 'april',
			'month_5'	=> 'mei',
			'month_6'	=> 'juni',
			'month_7'	=> 'juli',
			'month_8'	=> 'augustus',
			'month_9'	=> 'september',
			'month_10'	=> 'oktober',
			'month_11'	=> 'november',
			'month_12'	=> 'december',
			'day_1'		=> 'maandag',
			'day_2'		=> 'dinsdag',
			'day_3'		=> 'woensdag',
			'day_4'		=> 'donderdag',
			'day_5'		=> 'vrijdag',
			'day_6'		=> 'zaterdag',
			'day_7'		=> 'zondag',
			'of'		=> 'van',
			'about'		=> 'about',
			'about_link' => 'http://etaamb.blogspot.com/p/about.html',
			'year_index_of' => 'B.S. Index van het jaar',
			'year_index_of_pub' => 'B.S. Index van de publicaties van het jaar',
			'year_index_of_prom' => 'B.S. Index van de afkondigingen van het jaar',
			'year_description'=> 'Overzicht van de dagen met publicaties van het Belgisch Staatsblad van het jaar',
			'day_index_of'  => 'B.S. Index van',
			'day_index_of_pub'  => 'B.S. Index van de publicaties van',
			'day_index_of_prom'  => 'B.S. Index van de afkondigingen van',
			'day_quickmenu' => 'Snelle toegang',
			'day_description' => 'Lijst van document gepubliceerd in het Belgisch Staatsblad op',
			'doc_source' => 'bron',
			'doc_pub'	=> 'pub.',
			'doc_prom'	=> 'prom.',
			'doc_numac' => 'numac',
			'doc_type' => 'type',
			'numac_source' => 'bron',
			'numac_moniteur' => 'staatsblad',
			'numac_of' => ' van',
			'numac_document_of' => 'Dokument van',
			'numac_published_on' => 'gepubliceerd op',
			'numac_referer_title' => 'Uw %s opzoeking',
			'numac_referer_description' => 'De termen van uw zoekopdracht (%s) zijn gehighlighted in de tekst.',
			'numac_referer_deactivate'  => 'uitschakelen',
			'numac_list_title' => 'Relevante gevonden documenten',
			'title_of' => ' van',
			'title_source' => 'bron',
			'title_moniteur' => 'staatsblad',
			'keywords_list' => 'Sleutelwoorden',
			'etaamb_description' => '<b>Etaamb</b> biedt de inhoud van de Belgisch Staatsblad aan gesorteerd op afkondigings- en publicatiedatum, behandeld om  gemakkelijk leesbaar en afprintbaar te zijn, en verrijkt met een relationele context.',
			'linked_list' => 'Teksten waarnaar verwezen wordt in dit document: ',
			'reversed_list' => 'Teksten die naar dit document verwijzen:',
			'notype'	=> 'document',
            'title' => 'Etaamb',
			'moniteur'	=> 'Staatsblad',
			'my_error_title' => 'Request Fout',
			'my_error_oops' => 'Oeps...',
			'my_error_descrption' => 'Request fout',
			'my_error_intro' => 'De opvraag heeft de volgende foutboodschap veroorzaakt:',
			'my_error_url'   => 'De volgende URL kan dus fout zijn:',
			'my_error_balsem'=> 'De fout werd opgenomen en zal zo vlug mogelijk worden bestudeerd en behandeld.',
			'my_error_general' => 'De URL is niet erkend door Etaamb.',
			'my_error_numac' => 'Het document is niet aanwezig in de Databank. <br> Hij is dus onbestaand, niet opgenomen door Etaamb, of niet vertaald.',
			'my_error_year_invalid' =>  'Er zijn geen digitale edities van het Belgisch Staatsblad voor het opgegeven jaar.',
			'my_error_month_invalid' => 'Er zijn geen digitale edities van het Belgisch Staatsblad voor de opgegeven maand.',
			'my_error_day_invalid' =>   'Er zijn geen digitale edities van het Belgisch Staatsblad voor de opgegeven dag.',
			'my_error_naturalisation' => 'Om redenen van bescherming van het privé-leven, is het opgevraagde document tijdelijk onbeschikbaar.',
			'close'		=> 'sluiten',
			'interfacewords' => 'title numac',
			'hire_me'	=> 'Alhoewel zonder actief op zoek te zijn naar een baan, ben ik altijd beschikbaar voor innoverende projecten of interessante aanbiedingen. Als u een project heeft voor een web of mobile applicatie, een ontwikkelaar of gewoon wat expertise nodig hebt, kunnen we dat zeker wel bespreken.',
			'private_life'	=> 'privéleven',
			'priv_title'	=> 'Zijn uw gegevens weergegeven op deze pagina?',
			'priv_exp'		=> 'Indien u het wenst kunt u via het onderstaande formulier een aanvraag plaatsen om uw gegevens uit dit document, zoals beschikbaar op etaamb.be, te verwijderen.',
			'priv_text'		=> 'Titel van het document:',
			'priv_url'		=> 'Url van de betrokken pagina:',
			'priv_comment'	=> 'Opmerkingen:',
			'priv_mail'		=> 'E-mail adres:',
			'priv_data'		=> 'Te verwijderen woorden:',
			'priv_opt'		=> 'Optionele velden',
			'priv_send'		=> 'doorsturen',
			'rss_title_complete' 		=> 'Inhoudstafel van het Belgisch Staatsblad',
			'rss_description_complete'  => 'Al de inhoud van de laaste publicatie van het Belgisch Staatsblad, aangeboden via de website etaamb.be',
			'rss_signature'	=> 'Lees de volledige inhoud op etaamb.be !',
			'stopwords' => 'aan af al alles als ben bij daar dan dat de der deze die dit doch doen door dus een eens en er ge geen haar had heb hebben heeft hem het hier hij hoe hun iets ik in is ja je kan kon maar me meer men met mij mijn moet na naar niet niets nog nu of om omdat ons ook op over reeds te tegen toch toen tot u uit uw van veel voor want waren was wat we wel werd wezen wie wij wil zal ze zei zelf zich zij zijn zo zou'
            )
        );

    public function __construct($l)
        {
        $this->l = $l;
        }

    public function get($t,$l=false)
        {
		$lang = $l === false ?  $this->l : $l;
        if (!isset($this->langs[$lang][$t]))
            return "%$t%";
        $el = $this->langs[$lang][$t];

        if (is_array($el))
            {
            return $el[mt_rand(0,count($el)-1)];
            } 
        return $el;
        }

	public function l()
		{
		return $this->l;
		}
		
	public function p($t)
		{
		echo $this->get($t);
		}
    }
